/*
 * masterFrame.java
 *
 * Created on May 10, 2010, 9:38 AM
 */

package consistency.ui;


import java.awt.Font;
import java.awt.Insets;

import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.*;

import java.util.Vector;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.border.EtchedBorder;
import javax.swing.text.DefaultCaret;

import ame.ui.RestrictedFileSystemView;
import consistency.main.Run;
import consistency.main.Setup;
import ensdfparser.nds.latex.Translator;
import formatcheck.check.FormatCheck;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @author Jun
 */
public class FormatCheckFrame extends javax.swing.JFrame {
    
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    boolean isFileLoaded;
    
    Vector<File> filesV;
    
    consistency.main.Run run;

    
    public FormatCheckFrame() throws IOException {
        Translator.init();
        
        isFileLoaded=false; 
        
        initComponents();
        run=new consistency.main.Run() {
        	public String title() {
        		return formatCheckTitle();
        	}
        };
                
        pathField.setText(consistency.main.Setup.outdir);
        filesV=new Vector<File>();
        
        run.setFilesV(filesV);
        
        textArea.setFont(new Font("Courier New", Font.PLAIN, 12));
        textArea.setTransferHandler(new TransferHandler() {
            /**
             * 
             */
            private static final long serialVersionUID = 1L;

            public boolean canImport(TransferHandler.TransferSupport support) {
                if (!support.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                    return false;
                } 
                return true;
            }
     
            @SuppressWarnings("unchecked")
            public boolean importData(TransferHandler.TransferSupport support) {
                if (!canImport(support)) {
                    return false;
                }
                 
                Transferable t = support.getTransferable();
     
                try {
                    java.util.List<File> fileList=(java.util.List<File>)t.getTransferData(DataFlavor.javaFileListFlavor);
     
                    consistency.main.Setup.filedir=fileList.get(0).getAbsolutePath();
                    consistency.main.Setup.save();
                                 
                    run.clear();            
                    //run.printMessage(run.title());
                    
                    File[] files=new File[fileList.size()];
                    fileList.toArray(files);
                    
                    loadFiles(files);//load to lines only, not parsing ENSDF
                    
                } catch (UnsupportedFlavorException e) {
                    return false;
                } catch (Exception e) {
                    e.printStackTrace();
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, e);  
                    return false;
                }
     
                return true;
            }
        });
        
        run.setMessenger(textArea);
        //run.printMessage(run.formatCheckTitle()); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadButton = new javax.swing.JToggleButton();
        pathLabel = new javax.swing.JLabel();
        pathField = new javax.swing.JTextField();
        checkButton = new javax.swing.JToggleButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadButton.setText("Load ENSDF File(s)");
        
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        pathLabel.setText("Output path:");

        pathField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pathFieldPropertyChange(evt);
            }
        });
        pathField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pathFieldKeyReleased(evt);
            }
        });

        checkButton.setText("Start Checking");
        //checkButton.setToolTipText("<HTML>check format and consistency of records, generate tabulated output for levels<br>"
        //        +                        "and gammas grouped by energies, and also average values from different datasets.</HTML>");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        
        scrollPane = new JScrollPane();
        //scrollPane.setViewportBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null), "message", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));
        scrollPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(EtchedBorder.LOWERED),"message"));
        scrollPane.setToolTipText("display the processing status and message.");
        
        btnBrowse = new JButton("Browse");
        btnBrowse.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel = new JLabel("(a single file of multiple ENSDFs or load multiple files)");
        
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                frameMouseClicked(evt);
            }
        });
        
 
        
        //////////////////////////////////////////
        // LAYOUT
        /////////////////////////////////////////
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
            groupLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(groupLayout.createSequentialGroup()
                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                        .addGroup(groupLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                        .addGroup(groupLayout.createSequentialGroup()
                            .addGap(0)
                            .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                .addGroup(groupLayout.createSequentialGroup()
                                    .addGap(6)
                                    .addComponent(pathLabel)
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(pathField, 417, 417, 417)
                                    .addGap(18)
                                    .addComponent(btnBrowse, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE))
                                .addGroup(groupLayout.createSequentialGroup()
                                    .addGap(4)
                                    .addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(checkButton, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(groupLayout.createSequentialGroup()
                                            .addComponent(loadButton, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(ComponentPlacement.UNRELATED)
                                            .addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                                    .addGap(116)))
                            .addGap(9)))
                    .addGap(4))
        );
        groupLayout.setVerticalGroup(
            groupLayout.createParallelGroup(Alignment.LEADING)
                .addGroup(groupLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(loadButton)
                        .addComponent(lblNewLabel))
                    .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkButton)
                    .addGap(8)
                    .addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(pathField, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrowse)
                        .addComponent(pathLabel, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
        );
  

        groupLayout.setHonorsVisibility(false);
        
        textArea = new JTextArea();
        //textArea.addCaretListener(new CaretListener() {
        //  public void caretUpdate(CaretEvent e) {
        //      textArea.update(textArea.getGraphics());
        //      scrollPane.update(scrollPane.getGraphics());
        //  }
       // });
        
        textArea.setMargin(new Insets(5,5,5,5));
        textArea.setEditable(false);

        DefaultCaret caret = (DefaultCaret)textArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);
        //caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        //PrintStream printStream = new PrintStream(new CustomOutputStream(textArea));
        //System.setOut(printStream);
        
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.add(textArea);
        scrollPane.setViewportView(textArea);

        getContentPane().setLayout(groupLayout);
        
        pack();
        textArea.setVisible(true);
        scrollPane.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        
        isFileLoaded=false;
         try{
             run.clear();            
             //run.printMessage(run.title());
             
             //JFileChooser fc=new JFileChooser();
             JFileChooser fc;
             try {
                 fc = new JFileChooser(".");
              }catch (Exception e) {
                 fc = new JFileChooser(".", new RestrictedFileSystemView());
              }
             
             
             if(consistency.main.Setup.filedir!=null)
                 fc.setCurrentDirectory(new File(consistency.main.Setup.filedir));
             
             fc.setMultiSelectionEnabled(true);
             
             int ret=fc.showOpenDialog(this);
             if(ret==JFileChooser.APPROVE_OPTION){
                 consistency.main.Setup.filedir=fc.getCurrentDirectory().toString();
                 consistency.main.Setup.save();
    
                 File[] files=fc.getSelectedFiles();
                 //dataFile=fc.getSelectedFile();
                 
                 loadFiles(files);

             }       
         }catch(Exception e){
             e.printStackTrace();
             JOptionPane.showMessageDialog(this,e);         
         }

    }//GEN-LAST:event_loadButtonActionPerformed
       

    /*
     * open file only, not parsing ENSDF
     */
    private void loadFiles(File[] files) throws Exception{

        filesV.clear();
        
        if(files.length==1){
            File dataFile=files[0];
            run.printMessage("Loading file: "+dataFile.getAbsolutePath());
        }else if(files.length>1){
            run.printMessage("Loading files:");
            for(int i=0;i<files.length;i++){
                run.printMessage("    "+files[i].getAbsolutePath());        
            }
        }
                                        
        run.printMessage("Done loading");
                  
        for(int i=0;i<files.length;i++)      
            filesV.add(files[i]);
        
        isFileLoaded=true;
    }

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed

        if(!isFileLoaded){
            JOptionPane.showMessageDialog(this,"You should load a file or files for checking!");
            return;
        }
        
        boolean validOutdir=true;
        String message="";
        if(Setup.outdir.trim().length()==0){
            message="Error: output path is empty. ";           
            validOutdir=false;
        }else{ 
            File f=new File(Setup.outdir.trim());
            if(!f.exists()){
                message="Error: output path does not exist. ";
                validOutdir=false;
            }
        }
        
        if(!validOutdir){
            message+="Please specify output path.";
            run.printMessage(message);
            JOptionPane.showMessageDialog(this, message);
            return;
        }
        
        String outfilename=Setup.outdir+File.separator+"formatcheck";
        
        run.setOutFilename(outfilename);
        
        try{
            run.checkFormat(outfilename);                
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_tableButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {

        try{
            
            //JFileChooser fc=new JFileChooser();
            JFileChooser fc;
            try {
                fc = new JFileChooser(".");            
             }catch (Exception e) {
                fc = new JFileChooser(".", new RestrictedFileSystemView());
             }

            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setApproveButtonText("Select");
            fc.setApproveButtonToolTipText("Select this directory");
            
            if(Setup.outdir!=null)
                fc.setCurrentDirectory(new File(Setup.outdir));
            
            int ret=fc.showOpenDialog(this);
            if(ret==JFileChooser.APPROVE_OPTION){
                //Setup.outdir=fc.getSelectedFile().toString();
                
                File file = fc.getSelectedFile();
                Setup.outdir=file.getAbsolutePath();
                
                System.out.println();
                Setup.save();
                
                pathField.setText(Setup.outdir);
            }
            
           
        }catch(Exception e){
            //e.printStackTrace();
            String message="Error when selecting output path!";
            JOptionPane.showMessageDialog(this,message);
            run.printMessage(message);                                       
        }

   }

    private void pathFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pathFieldPropertyChange
        
    }//GEN-LAST:event_pathFieldPropertyChange

    private void pathFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathFieldKeyReleased
        //specifies the path that output will be created in
        consistency.main.Setup.outdir=pathField.getText();
        consistency.main.Setup.save();
    }//GEN-LAST:event_pathFieldKeyReleased
    
    
    private void frameMouseClicked(java.awt.event.MouseEvent e) {
        
        //if ((e.getModifiers() & ActionEvent.CTRL_MASK) ==ActionEvent.CTRL_MASK) {
        //  System.out.println("CTRL KEY PRESSED");
        //}
        
        if(e.getButton()==1 && e.isControlDown() && e.getClickCount()>=2) {//ctrl + left double click
            
            String title="Wrap up comment lines to 80-column format";
            LineWrappingFrame frame=null;
            java.awt.Frame[] frames=java.awt.Frame.getFrames();
            for(int i=0;i<frames.length;i++) {
                if(frames[i].getTitle().equals(title))
                    frame=(LineWrappingFrame)frames[i];
                
                //System.out.println(frames[i].getName()+"  "+frames[i].getTitle());
            }
            
            if(frame==null) {
                frame=new LineWrappingFrame();
                frame.setTitle(title);
                frame.setLocation(this.getX()+this.getWidth()+5,this.getY()+5);
                frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                frame.setResizable(false);
            }

            frame.setVisible(true);
            
        }
    }

    public static void main(String[] args)throws Exception{
        Setup.load();
        Translator.init();       
        
        if(args.length==0)
            runUI();
        else
            runCommand(args);
       
        
        //test();

    }
    
    static void test() throws Exception {
        String filePath="",fileDir="";
        String os=System.getProperty("os.name").toLowerCase();
        if(os.contains("mac"))
            fileDir="/Users/chenj/work/evaluation/ENSDF/check/";
        else
            fileDir="H:\\work\\evaluation\\ENSDF\\check\\";
        
        filePath=fileDir+"check.ens";
        
        String[] args=new String[] {filePath};
        runCommand(args);
        
    }
        
    static void runUI()throws Exception{
        try{
            
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        }catch(Exception e1){
            try{
                for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                    else{
                        UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    }
                }
                
            }catch(Exception e2){
                
            }           
        }
        Run run=new Run();
        
        FormatCheckFrame frame=new consistency.ui.FormatCheckFrame();
        frame.setTitle("ENSDF format check "+run.version());
        frame.setVisible(true);
        frame.setResizable(false);
    }

    static void runCommand(String[] args) throws Exception{
        //Control settings are reset in Run() constructor
        Run run=new Run();
        
        System.out.println("Start running FormatCheck(args): first argument must be the path to an ENSDF file.");
        if(args.length==0){
            System.out.println("Error: no ENSDF file path is given!");
            return;
        }
        
        
        String s=args[0].toUpperCase();
        
        /*
        if(args.length==1 && (s.contains("-HELP")||s.contains("-USAGE"))){
            System.out.println(run.usage());        
            return;
        }
        */
        
        if(args[0].charAt(0)=='-'){
            System.out.println("Error: no input ENSDF file!\n");
            return;
        }
        
        
        File f=new File(args[0]);
        if(!f.exists()){
            System.out.println("Error: ENSDF file does not exist or wrong file path:");
            System.out.println(" "+f.getAbsolutePath());
            return;
        }
        
        //set file to check
        Vector<File> filesV=new Vector<File>();
        filesV.add(f);
        run.setFilesV(filesV);

        
        String indir="",outdir="";
        File parentFile=f.getAbsoluteFile().getParentFile();
        if(parentFile==null)
            indir=".";
        else
            indir=parentFile.getAbsolutePath();
        
        outdir=indir;
        
        int count=1;
        if(args.length>1 && ((String)args[1]).trim().charAt(0)!='-'){
            count++;
        }
        
        
        //other options, all options begin with '-'
        //skip the option otherwise
        for(int i=count;i<args.length;i++){
            s=((String)args[i]).trim();
            if(s.charAt(0)!='-')
                continue;
            
            while(s.length()>0 && s.charAt(0)=='-')
                s=s.substring(1);
            
            s=s.trim();
            if(s.length()<=0)
                continue;
            
            s=s.toUpperCase();
        }
               
        File dir=new File(outdir);
        if(!dir.exists())
            dir.mkdir();
           
        consistency.main.Setup.filedir=indir;     
        consistency.main.Setup.outdir=indir;
        consistency.main.Setup.save();

        
        String outfilename=Setup.outdir+File.separator+"formatcheck";
        
        run.setOutFilename(outfilename);
        
        try{
            run.checkFormat(outfilename);  
            
            run.redirectOutputToMessenger(false);
            
            FormatCheck formatCheck=run.getFormatCheck();
            System.out.println("See checking report in:\n  "+outfilename+".fmt");
            String s1=formatCheck.getStatistics().trim();
            System.out.println("\n*** "+s1+" ***"+"\n");
            
        }catch(Exception e){
            e.printStackTrace();
        }


    }     
    // Variables declaration - do not modify//GEN-BEGIN:variables


    private javax.swing.JToggleButton loadButton;
    private javax.swing.JTextField pathField;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JToggleButton checkButton;

    private JScrollPane scrollPane;
    private JTextArea textArea;
    private JButton btnBrowse;

}